'use client';
import {useEffect,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {ChevronDown,ChevronUp,Upload,FileText,Plus,X,Download,CheckCircle2,Clock,Pencil} from 'lucide-react';
import {planoSchema,montarParcelas,resumoParcelamento,exemploPlano,type PlanoInput,type PlanoMeta,type Parcela,filtrarParcelas,guiaLiberada,dataLiberacaoParcela,ajustarVencimentosPrevistos,type FiltroParcelas} from '@/lib/parcelamentos';
import {lerParcelamentoAction,criarPlanoAction,pedirGuiaAction,publicarGuiaParcelaAction,renomearPlanoAction,type ParcelamentoArea} from './actions';
import {marcarGuiaPagaAction} from '@/app/(portal)/minha-contabilidade/guias/actions';
import {Card} from '@/components/ui/Card';
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(s:string)=>s.slice(0,10).split('-').reverse().join('/');
const field='mt-1 w-full rounded-xl border border-black/10 dark:border-white/10 bg-surface-card p-2.5 text-sm text-ink focus:outline-none focus:ring-2 focus:ring-hexxa-lime/40';
const button='tap-target pressable focusable inline-flex items-center justify-center gap-2 rounded-full border border-black/10 dark:border-white/10 bg-surface-card px-4 py-2 text-xs font-semibold text-ink shadow-(--elev-1) disabled:opacity-40 disabled:cursor-not-allowed';
const fields:[keyof PlanoInput,string,string][]=[['description','Descrição','text'],['tax','Tributo','text'],['authority','Órgão responsável','text'],['agreement','Número do acordo','text'],['cnpj','CNPJ do documento','text'],['totalAmount','Valor consolidado (R$)','number'],['installmentCount','Número de parcelas','number'],['installmentAmount','Parcela base (R$)','number'],['firstAmount','Primeira parcela / entrada (R$)','number'],['firstDueDate','Primeiro vencimento','date'],['paidCount','Parcelas iniciais já pagas','number']];
export default function ParcelamentosHub({initialGuides=[],initialPlans=[],area='cliente',companyId,demo=false,blockedReason,novasParcelas=[]}:{initialGuides?:Parcela[];initialPlans?:PlanoMeta[];area?:ParcelamentoArea;companyId?:string;demo?:boolean;blockedReason?:string;novasParcelas?:string[]}) {
 const router=useRouter();const [busy,start]=useTransition();
 const [guides,setGuides]=useState(initialGuides);const [plans,setPlans]=useState(initialPlans);
 const [expanded,setExpanded]=useState<string|null>(null);const [adding,setAdding]=useState(false);
 const [draft,setDraft]=useState<Record<string,unknown>>({paidCount:0,agreement:''});const [importId,setImportId]=useState<string|undefined>();const [warnings,setWarnings]=useState<string[]>([]);
 const [filters,setFilters]=useState<Record<string,FiltroParcelas>>({});const [editing,setEditing]=useState<string|null>(null);const [name,setName]=useState('');
 const [notice,setNotice]=useState('');const [sending,setSending]=useState<Parcela|null>(null);
 useEffect(()=>{const refresh=()=>router.refresh();window.addEventListener('focus',refresh);return ()=>window.removeEventListener('focus',refresh);},[router]);
 useEffect(()=>{if(!demo){setGuides(initialGuides);setPlans(initialPlans);}},[initialGuides,initialPlans,demo]);
 const today=demo?'2026-09-30':new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
 const groups=new Map<string,Parcela[]>();for(const g of ajustarVencimentosPrevistos(guides,plans,today)){if(g.installmentGroupId)groups.set(g.installmentGroupId,[...(groups.get(g.installmentGroupId)||[]),g]);}
 const apply=(r:{guides:Parcela[];plans:PlanoMeta[]})=>{setGuides(r.guides);setPlans(r.plans);router.refresh();};
 const fileUrl=(id:string,original=false,download=false)=>`/api/parcelamentos/${id}/arquivo?${new URLSearchParams({...(area==='contador'?{area:'contador',companyId:companyId || ''}:{}),...(original?{origem:'termo'}:{}),...(download?{modo:'baixar'}:{})})}`;
 const example=()=>{setDraft({...exemploPlano});setImportId('demo-import');setWarnings(['Exemplo fictício. Nenhum arquivo foi enviado à IA e nenhuma parcela foi gravada no banco.']);};
 async function read(file:File) {
  start(async()=>{setNotice('');setImportId(undefined);setDraft({paidCount:0,agreement:''});setWarnings([]);try{
   if(demo){example();return;}
   const fd=new FormData();fd.set('file',file);const r=await lerParcelamentoAction(area,companyId,fd);
   if(!r.ok){setNotice(r.message);return;}setDraft(r.data);setImportId(r.id);setWarnings(r.warnings);
  }catch{setNotice('Falha ao ler o PDF. Tente novamente ou preencha os campos.');}});
 }
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const confirm=new FormData(e.currentTarget).get('history')==='on';
  start(async()=>{setNotice('');try{const p=planoSchema.parse(draft);
   if(p.paidCount>0 && !confirm){setNotice('Confirme o histórico de parcelas pagas.');return;}
   if(demo){const existing=plans.find(x=>p.agreement && x.agreement.toLowerCase()===p.agreement.toLowerCase() && x.authority.toLowerCase()===p.authority.toLowerCase());if(existing){setExpanded(existing.id);setAdding(false);setNotice('Este acordo já foi importado. As parcelas existentes foram preservadas.');return;}const id=crypto.randomUUID();const rows=montarParcelas(p,today).map(r=>({id:`${id}-${r.number}`,taxName:`Parcelamento — ${p.tax} (${r.number}/${p.installmentCount})`,referenceMonth:r.referenceMonth,amount:r.amount,dueDate:r.dueDate,status:r.status,fileUrl:null,pixCode:null,installmentGroupId:id,installmentNumber:r.number,installmentCount:p.installmentCount,installmentEstimated:true}));setGuides(g=>[...rows,...g]);setPlans(ps=>[{id,description:p.description,tax:p.tax,authority:p.authority,agreement:p.agreement,totalAmount:p.totalAmount,sourceName:importId?'Recibo de adesão — exemplo.pdf':null},...ps]);setExpanded(id);setAdding(false);setNotice('Prévia: parcelas geradas em memória.');return;}
   const r=await criarPlanoAction(area,companyId,p,importId,confirm);if(!r.ok){setNotice(r.message);return;}apply(r);setExpanded(r.id);setAdding(false);setNotice(r.existing?'Este documento/acordo já foi importado. As parcelas existentes foram preservadas.':'Parcelamento cadastrado. As parcelas foram geradas automaticamente.');
  }catch(e){setNotice(e instanceof Error ? ('issues' in e ? 'Confira os campos obrigatórios, valores, CNPJ e datas.':e.message):'Não foi possível cadastrar.');}});
 }
 function request(g:Parcela){start(async()=>{if(demo){setGuides(gs=>gs.map(p=>p.id===g.id?{...p,requestedAt:today}:p));setNotice('Prévia: solicitação registrada para o contador.');return;}const r=await pedirGuiaAction(g.id);setNotice(r.message);if(r.ok)apply(r);});}
 function pay(g:Parcela){start(async()=>{if(demo){setGuides(gs=>gs.map(p=>p.id===g.id?{...p,status:'PAID'}:p));setNotice('Prévia: pagamento confirmado em memória.');return;}const r=await marcarGuiaPagaAction(g.id);if('error' in r){setNotice(r.error || 'Falha ao confirmar.');return;}setGuides(gs=>gs.map(p=>p.id===g.id?{...p,status:'PAID'}:p));setNotice('Pagamento registrado.');router.refresh();});}
 function send(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);start(async()=>{if(!sending)return;
  if(demo){const f=fd.get('file') as File;if(!f?.size){setNotice('Selecione o PDF da guia.');return;}const url=URL.createObjectURL(f);setGuides(gs=>gs.map(p=>p.id===sending.id?{...p,fileUrl:url,amount:Number(fd.get('amount')),dueDate:String(fd.get('due')),installmentEstimated:false}:p));setSending(null);setNotice('Prévia: guia anexada em memória, sem envio real.');return;}
  const r=await publicarGuiaParcelaAction(companyId || '',sending.id,fd);setNotice(r.message);if(r.ok){apply(r);setSending(null);}
 });}
 function rename(e:React.FormEvent,id:string){e.preventDefault();start(async()=>{try{
  if(demo){setPlans(ps=>ps.map(p=>p.id===id?{...p,description:name.trim()}:p));setEditing(null);setNotice('Prévia: nome atualizado em memória.');return;}
  const r=await renomearPlanoAction(area,companyId,id,name);if(!r.ok){setNotice(r.message);return;}
  setPlans(ps=>ps.map(p=>p.id===id?{...p,description:r.plan.description}:p));setEditing(null);setNotice('Nome do parcelamento atualizado.');router.refresh();
 }catch{setNotice('Não foi possível alterar o nome. Tente novamente.');}});}
 function guideActions(p:Parcela,spotlight=false){
  const release=dataLiberacaoParcela(p),ready=guiaLiberada(p,today);
  return <span className="flex flex-wrap items-center gap-2">
   {p.fileUrl && <>{novasParcelas.includes(p.id) && <span className="rounded-full bg-hexxa-lime/15 px-2 py-1 text-[10px] font-semibold text-ink">Nova guia</span>}<a className={button} target="_blank" rel="noopener noreferrer" href={demo?p.fileUrl:fileUrl(p.id,false,spotlight)}>{spotlight?<><Download size={13}/>Baixar guia do mês</>:'Ver guia'}</a></>}
   {p.status!=='PAID' && !p.fileUrl && (!ready?<span className="rounded-full border border-black/5 dark:border-white/10 px-3 py-2 text-xs text-ink-soft"><Clock size={12} className="mr-1 inline"/>Guia a partir de {date(release!)}</span>:area==='contador'?<button disabled={busy} className={button} onClick={()=>setSending(p)}><Upload size={13}/>{spotlight?'Enviar guia do mês':'Anexar e enviar guia'}</button>:<button disabled={busy || !!p.requestedAt} className={button} onClick={()=>request(p)}><Clock size={13}/>{p.requestedAt?'Solicitada ao contador':spotlight?'Solicitar guia do mês':'Solicitar guia'}</button>)}
   {!spotlight && area==='cliente' && p.status!=='PAID' && p.fileUrl && !p.installmentEstimated && <button disabled={busy} className={button} onClick={()=>pay(p)}><CheckCircle2 size={13}/>Marcar como paga</button>}
  </span>;
 }
 return <div className="space-y-5 text-ink">
  {demo && <div className="flex flex-wrap justify-between gap-3 rounded-xl bg-[#C6FF3D] p-3 text-xs font-semibold text-ink"><span>Prévia local · Dados fictícios · Sem IA externa ou gravação no banco</span><span className="flex gap-3"><a href="/previa/parcelamentos" className="underline">Cliente</a><a href="/previa/parcelamentos?area=contador" className="underline">Contador</a></span></div>}
  <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">Parcelamentos</h2><p className="mt-1 text-xs text-ink-soft">Do recibo de adesão às parcelas organizadas. A guia oficial de cada mês vem da contabilidade.</p></div><button disabled={busy || !!blockedReason} className={`${button} bg-hexxa-forest text-hexxa-lime dark:bg-hexxa-lime dark:text-hexxa-forest`} onClick={()=>{setAdding(true);setImportId(undefined);setDraft({paidCount:0,agreement:''});setWarnings([]);setNotice('');}}><Plus size={14}/> Novo parcelamento</button></header>
  {notice && <p role="status" className="rounded-xl border border-black/10 dark:border-white/10 bg-surface-card p-3 text-sm text-ink">{notice}</p>}
  {blockedReason && <p role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{blockedReason}</p>}
  {adding && !blockedReason && <form onSubmit={save} className="space-y-4 rounded-2xl border border-black/10 dark:border-white/10 bg-surface-card p-5 text-ink"><div className="flex justify-between"><h3 className="font-semibold">Importar parcelamento</h3><button aria-label="Fechar cadastro" type="button" onClick={()=>setAdding(false)}><X size={18}/></button></div><label className="block cursor-pointer rounded-xl border border-dashed border-black/20 dark:border-white/20 bg-surface-card p-5"><span className="flex items-center gap-2 text-sm"><Upload size={18}/> Subir recibo ou termo de parcelamento</span><span className="mt-1 block text-xs text-ink-soft">PDF até 3 MB. A IA preenche os dados para você conferir.</span><input aria-label="PDF do parcelamento" type="file" accept="application/pdf" disabled={busy} className="mt-3 text-xs" onChange={e=>{if(e.target.files?.[0])void read(e.target.files[0]);}}/></label>{demo && <button type="button" className={button} onClick={example}>Usar documento de exemplo</button>}{busy && <p role="status" className="text-xs">Processando…</p>}{importId && !demo && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-xs text-emerald-900">Documento reconhecido como parcelamento. CNPJ do contribuinte conferido com a empresa aberta no Hub.</p>}{warnings.length>0 && <div className="rounded-xl bg-amber-50 p-3 text-xs text-amber-900">{warnings.map((w,i)=><p key={i}>{w}</p>)}</div>}<div className="grid gap-3 sm:grid-cols-2">{fields.map(([key,label,type])=><label key={key} className={`text-xs ${key==='description'?'sm:col-span-2':''}`}>{label}<input required={key!=='agreement'} aria-label={label} type={type} maxLength={type==='text'?180:undefined} min={type==='number'?key==='paidCount'?0:key==='installmentCount'?2:0.01:undefined} max={key==='installmentCount'||key==='paidCount'?240:undefined} readOnly={key==='cnpj' && !!importId && !demo} step={type==='number'?key==='installmentCount'||key==='paidCount'?1:0.01:undefined} value={typeof draft[key]==='string'||typeof draft[key]==='number'?String(draft[key]):''} className={field} onChange={e=>setDraft(d=>({...d,[key]:type==='number'?e.target.value===''?null:Number(e.target.value):e.target.value}))}/></label>)}</div>{Number(draft.paidCount)>0 && <label className="flex items-start gap-2 text-xs"><input type="checkbox" name="history" required/>Confirmo que as parcelas iniciais informadas estão pagas, conforme o documento. Esta importação registra o histórico e não movimenta o banco.</label>}<p className="text-xs text-ink-soft">A programação mensal usa a parcela base; atualizações e juros serão confirmados na guia oficial. Confira entrada diferenciada, vencimentos e histórico antes de gerar.</p><button disabled={busy} className={`${button} bg-hexxa-forest text-hexxa-lime dark:bg-hexxa-lime dark:text-hexxa-forest`}>Confirmar e gerar parcelas</button></form>}
  {!groups.size && <p className="rounded-2xl border border-dashed p-8 text-center text-sm text-ink-soft">Nenhum parcelamento cadastrado. Importe o recibo ou preencha o cadastro.</p>}
  {[...groups.entries()].map(([id,rows])=>{
   const meta=plans.find(p=>p.id===id),s=resumoParcelamento(rows,today),open=expanded===id,current=s.current;
   const filter=filters[id] || 'primeiras12',visible=filtrarParcelas(s.sorted,filter,today);
   const novasDoPlano=rows.filter(p=>novasParcelas.includes(p.id)).length;
   return <Card key={id} className="overflow-hidden p-0 sm:p-0">
    <button aria-expanded={open} className={`focusable flex w-full items-start justify-between gap-4 text-left ${open?'p-5 sm:p-6':'p-4 pb-3 sm:px-6'}`} onClick={()=>setExpanded(open?null:id)}>
     <span className="min-w-0">
      <span className={`block font-semibold text-ink ${open?'font-serif text-lg':'line-clamp-1 text-sm'}`}>{meta?.description || rows[0]?.taxName.replace(/\s*\(\d+\/\d+\)$/,'')}</span>
      <span className="mt-2 block text-xs text-ink-soft">{s.paid} pagas · {s.remaining} restantes{novasDoPlano>0 && <span className="ml-2 inline-block rounded-full bg-hexxa-lime/15 px-2 py-0.5 font-semibold text-ink">{novasDoPlano} {novasDoPlano===1?'nova guia':'novas guias'}</span>}</span></span>
     <span className="flex shrink-0 items-start gap-3">
      {!open && current && <span className="text-right"><span className="block text-sm font-semibold tabular text-ink">{money(current.amount)}</span><span className="mt-1 block text-[10px] text-ink-soft">Parcela{current.installmentEstimated?' · previsão':''}</span></span>}
      {open?<ChevronUp className="mt-1 text-ink-soft" size={16}/>:<ChevronDown className="mt-1 text-ink-soft" size={16}/>}
     </span>
    </button>
    <div className={`sm:mx-6 ${open?'mx-5 mb-5 sm:mb-6':'mx-4 mb-4'}`}>
     {open && meta && <div className="mb-4">{editing===id?<form onSubmit={e=>rename(e,id)} className="flex flex-wrap items-end gap-2"><label className="min-w-52 flex-1 text-xs text-ink-soft">Nome do parcelamento<input aria-label="Nome do parcelamento" required minLength={3} maxLength={180} value={name} onChange={e=>setName(e.target.value)} className={field}/></label><button disabled={busy} className={button}>Salvar nome</button><button type="button" className={button} onClick={()=>setEditing(null)}>Cancelar</button></form>:<button className="focusable inline-flex items-center gap-1.5 text-xs text-ink-soft hover:text-ink" onClick={()=>{setEditing(id);setName(meta.description);}}><Pencil size={12}/>Editar nome</button>}</div>}
     <div role="progressbar" aria-label="Parcelas pagas" aria-valuenow={s.paid} aria-valuemin={0} aria-valuemax={rows[0]?.installmentCount || rows.length} className="h-1.5 rounded-full bg-black/5 dark:bg-white/10"><div className="h-full rounded-full bg-hexxa-forest dark:bg-hexxa-lime" style={{width:`${s.paid/(rows[0]?.installmentCount || rows.length)*100}%`}}/></div>
     {open && <div className="mt-4 space-y-3 text-xs text-ink-soft"><div className="flex flex-wrap justify-between gap-3"><span>Órgão: <strong className="text-ink">{meta?.authority || 'Ver descrição'}</strong>{meta?.agreement && <> · Acordo: <strong className="text-ink">{meta.agreement}</strong></>}</span><span>Valor consolidado: <strong className="text-ink tabular">{money(meta?.totalAmount || s.total)}</strong></span></div><div className="flex flex-wrap justify-between gap-3"><span>Saldo das parcelas: <strong className="text-ink tabular">{money(s.balance)}</strong>{rows.some(p=>p.installmentEstimated && p.status!=='PAID')?' · sujeito a atualização':''}</span><span>Tributo: <strong className="text-ink">{meta?.tax || 'Ver descrição'}</strong></span></div></div>}
     {open && current && <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/5 dark:border-white/5 bg-surface-card p-4 shadow-(--elev-inset)"><span className="text-xs"><strong>{current.dueDate.slice(0,7)===today.slice(0,7)?'Parcela do mês':'Próxima pendência'} · {current.installmentNumber}/{current.installmentCount}</strong><span className="mt-1 block text-ink-soft">{date(current.dueDate)} · {money(current.amount)}{current.installmentEstimated?' · previsão':''}</span></span>{guideActions(current,true)}</div>}
    </div>
    {open && <div className="border-t border-black/10 dark:border-white/10">
     <div className="flex flex-wrap items-center justify-between gap-3 px-5 py-4 sm:px-6"><label className="text-xs text-ink-soft">Exibir parcelas<select aria-label="Exibir parcelas" value={filter} onChange={e=>setFilters(f=>({...f,[id]:e.target.value as FiltroParcelas}))} className={field}><option value="primeiras12">12 primeiras parcelas</option><option value="ano">Ano corrente ({today.slice(0,4)})</option><option value="todas">Todas as parcelas</option></select></label><span className="text-xs text-ink-soft">Exibindo {visible.length} de {s.sorted.length} parcelas</span>{meta?.sourceName && (demo?<span className="text-xs text-ink-soft">Documento de origem: {meta.sourceName}</span>:<a className="text-xs text-ink-soft underline" href={fileUrl(id,true)} target="_blank" rel="noopener noreferrer"><FileText size={13} className="mr-1 inline"/>Ver recibo de adesão</a>)}</div>
     {!visible.length && <p className="px-5 py-5 text-sm text-ink-soft">Nenhuma parcela neste ano. Selecione outro filtro para consultar o plano.</p>}
     {visible.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-black/5 dark:border-white/5 px-5 py-3 text-xs sm:px-6"><span><strong>Parcela {p.installmentNumber}/{p.installmentCount}</strong><span className="ml-3 text-ink-soft">{date(p.dueDate)} · {money(p.amount)}</span><span className="mt-1 block text-ink-soft">{p.status==='PAID'?'Paga':p.status==='OVERDUE'?'Em atraso':'A vencer'}{p.installmentEstimated ? p.status==='PAID'?' · histórico do documento':' · valor previsto':''}{p.requestedAt && !p.fileUrl?' · solicitada ao contador':''}</span></span>{guideActions(p)}</div>)}
    </div>}
   </Card>;
  })}
  {sending && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-label="Enviar guia da parcela" onSubmit={send} className="w-full max-w-md space-y-4 rounded-2xl bg-surface-card p-6 text-ink"><div className="flex justify-between"><h3 className="font-semibold">Enviar parcela {sending.installmentNumber}/{sending.installmentCount}</h3><button type="button" aria-label="Fechar envio" onClick={()=>setSending(null)}><X size={18}/></button></div><label className="block text-xs">PDF da guia oficial<input aria-label="PDF da guia oficial" type="file" name="file" accept="application/pdf" required className={field}/></label><label className="block text-xs">Valor oficial (R$)<input type="number" step="0.01" min="0.01" name="amount" required defaultValue={sending.amount} className={field}/></label><label className="block text-xs">Vencimento oficial<input type="date" name="due" required defaultValue={sending.dueDate} className={field}/></label><label className="block text-xs">Pix desta parcela (opcional)<input name="pix" maxLength={1000} className={field}/></label><p className="text-xs text-ink-soft">Atualiza a parcela existente e entrega o PDF ao cliente com protocolo.</p><button disabled={busy} className={`${button} bg-hexxa-forest text-hexxa-lime dark:bg-hexxa-lime dark:text-hexxa-forest`}>Anexar e enviar ao cliente</button></form></div>}
 </div>;
}
