 'use client';
import {useState} from 'react';
import {itensDoRecebimento,validarDiscriminacao,type ReciboItem} from '@/lib/recibo-rules';
import type {ReceiptCandidate} from '@/lib/server/recibos';
export default function Discriminacao({candidate,expenses,onSave,onClose,busy}:{candidate:ReceiptCandidate;expenses:{id:string;description:string;amount:number}[];onSave:(items:ReciboItem[])=>void;onClose:()=>void;busy:boolean}) {
 const [items,setItems]=useState<ReciboItem[]>(candidate.itens || itensDoRecebimento(candidate));
 const [error,setError]=useState('');
 const total=items.reduce((s,i)=>s+(i.desconto ? -i.valor : i.valor),0);
 const update=(n:number,patch:Partial<ReciboItem>)=>setItems(items.map((i,k)=>k===n ? {...i,...patch}:i));
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-label="Discriminação dos valores" className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-[#F5F6F4] p-7 text-[#141615]" onSubmit={e=>{e.preventDefault();try{onSave(validarDiscriminacao(items,candidate.amount));}catch(e){setError((e as Error).message);}}}>
 <div className="flex justify-between"><h2 className="font-serif text-2xl">Discriminação dos valores</h2><button type="button" onClick={onClose}>Fechar</button></div>
 <p className="my-4 text-xs leading-relaxed">Principal, juros e descontos vêm do recebimento. Inclua apenas despesas cobradas neste pagamento. A soma deve fechar com o valor recebido; o lançamento financeiro permanece com o mesmo total.</p>
 <div className="space-y-3">{items.map((item,index)=><div key={index} className="flex flex-wrap gap-2 rounded-xl bg-white p-3"><label className="min-w-48 flex-1 text-xs">Descrição<input aria-label={`Descrição ${index+1}`} required maxLength={90} className="mt-1 w-full rounded border p-2" value={item.descricao} onChange={e=>update(index,{descricao:e.target.value})}/></label><label className="w-28 text-xs">Valor (R$)<input aria-label={`Valor ${index+1}`} type="number" step="0.01" min="0.01" required className="mt-1 w-full rounded border p-2" value={item.valor || ''} onChange={e=>update(index,{valor:Number(e.target.value)})}/></label><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={!!item.desconto} disabled={!!item.despesaId} onChange={e=>update(index,{desconto:e.target.checked})}/>Desconto</label><button type="button" className="text-xs underline" onClick={()=>setItems(items.filter((_,k)=>k!==index))}>Remover</button>{item.despesaId && <p className="w-full text-[11px] text-[#5F6E46]">Vinculado à despesa registrada</p>}</div>)}</div>
 <div className="my-4 flex flex-wrap gap-3"><button disabled={items.length>=8} type="button" className="rounded-full border px-4 py-2 text-xs" onClick={()=>setItems([...items,{descricao:'',valor:0}])}>Adicionar item</button><select aria-label="Vincular despesa registrada" disabled={items.length>=8} value="" className="max-w-full rounded border p-2 text-xs" onChange={e=>{const expense=expenses.find(x=>x.id===e.target.value);if(expense)setItems([...items,{descricao:expense.description.slice(0,90),valor:expense.amount,despesaId:expense.id}]);}}><option value="">Vincular despesa registrada…</option>{expenses.filter(x=>!items.some(i=>i.despesaId===x.id)).map(x=><option key={x.id} value={x.id}>{x.description} · R$ {x.amount.toFixed(2)}</option>)}</select></div>
 <p className="text-sm">Discriminado: R$ {total.toFixed(2)} · Recebido: R$ {candidate.amount.toFixed(2)}</p>{error && <p role="alert" className="mt-3 text-sm text-rose-700">{error}</p>}
 <button disabled={busy} className="mt-5 w-full rounded-full bg-[#2F4A3C] p-3 text-sm text-[#DFFFAE]">{busy ? 'Salvando…':'Salvar discriminação'}</button></form></div>;
}
