'use client';
import { useEffect, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { FileText, Download, Send, Share2, CalendarDays, Check, ArrowUpRight, Search, X, Clock3, Plus, Ban } from 'lucide-react';
import type { ReceiptRow, ReceiptCandidate, ReceiptScheduleRow } from '@/lib/server/recibos';
import Discriminacao from './Discriminacao';
import { executarReciboAction } from './actions';

const brl = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const fmt = (s: string | null) => s ? s.split('-').reverse().join('/') : 'A receber';
const inputClass = 'w-full rounded-xl border border-black/10 bg-white p-3 text-sm text-[#141615] focus:outline-none focus:ring-2 focus:ring-[#DFFFAE] dark:border-white/15 dark:bg-[#1C201C] dark:text-white';
const actionClass = 'inline-flex items-center gap-1.5 rounded-lg px-2.5 py-2 text-xs font-semibold hover:bg-black/5 disabled:opacity-40 dark:hover:bg-white/10';
const fiscalLabel: Record<string, string> = { NAO_APLICAVEL: 'Comprovação de pagamento', AGUARDANDO_CONFIGURACAO: 'Configuração fiscal pendente', PENDENTE: 'Pendente no ONEFLOW', ENVIADO: 'Enviado ao ONEFLOW', ENVIANDO: 'Envio em andamento', INCERTO: 'Conferir envio', ERRO: 'Falha no envio' };

export default function RecibosClient(props: { receipts: ReceiptRow[]; candidates: ReceiptCandidate[]; schedules: ReceiptScheduleRow[]; holding: boolean; demo?: boolean; signing?:{signerName:string}|null; expenses?: {id:string;description:string;amount:number}[] }) {
  const router = useRouter();
  const [signing,setSigning]=useState(props.signing || null);
  const [signatureModal,setSignatureModal]=useState(false);
  const [discrimination,setDiscrimination]=useState<ReceiptCandidate|null>(null);
  const [receipts, setReceipts] = useState(props.receipts);
  const [candidates, setCandidates] = useState(props.candidates);
  const [schedules, setSchedules] = useState(props.schedules);
  const [tab, setTab] = useState<'emitidos' | 'pendentes' | 'agendados'>('emitidos');
  const [search, setSearch] = useState('');
  const [busy, start] = useTransition();
  const [notice, setNotice] = useState<{ ok: boolean; message: string } | null>(null);
  const [share, setShare] = useState<string | null>(null);
  const [modal, setModal] = useState<{ action: 'email' | 'cancelar' | 'agendar' | 'emitir'; id: string } | null>(null);
  useEffect(() => {
    if (!props.demo) { setReceipts(props.receipts); setCandidates(props.candidates); setSchedules(props.schedules); setSigning(props.signing || null); }
  }, [props.receipts,props.candidates,props.schedules,props.demo,props.signing]);
  const pdf = (r: ReceiptRow, download = false) => props.demo
    ? `/api/recibo/preview?${new URLSearchParams({ exemplo:'true', tipo:props.holding ? 'holding' : 'pagamento', numero:r.number, valor:String(r.amount), pagador:r.payer, descricao:r.description, mes:r.referenceMonth, pagamento:r.paidAt, nota:r.invoiceNumber || '', itens:JSON.stringify(r.itens || []), ...(r.signed ? {assinado:'true'} : {}), ...(download ? { download:'true' } : {}) })}`
    : `/api/recibos/${r.id}${download ? '?download=true' : ''}`;
  const run = (p: Parameters<typeof executarReciboAction>[0]) => {
    setShare(null);
    start(async () => {
      if (props.demo) {
        if(p.action==='assinatura') {setSigning(p.active ? {signerName:'Filipe Heck — exemplo'} : null);setSignatureModal(false);}
        if(p.action==='discriminar') { setCandidates(cs=>cs.map(c=>c.id===p.id ? {...c,itens:p.itens}:c));setDiscrimination(null); }
        if (p.action === 'emitir') {
          const c = candidates.find(c => c.id === p.id)!;
          if (!c.paidAt || c.status !== 'PAID') { setNotice({ ok: false, message: 'Registre o pagamento antes de emitir a quitação.' }); return; }
          setReceipts(rs => [{ id: `demo-${c.id}`, entryId: c.id, number: `REC-202609-${c.id.slice(-6).toUpperCase()}`, amount: c.amount,
            signed:p.sign!==false && !!signing, itens:c.itens, description: c.description, payer: c.payer || p.name || 'Cliente', referenceMonth: '09/2026', paidAt: fmt(c.paidAt), issuedAt: '30/09/2026', fiscalEligible: props.holding && c.source === 'RENT', oneflowStatus: props.holding && c.source === 'RENT' ? 'AGUARDANDO_CONFIGURACAO' : 'NAO_APLICAVEL', canceled: false, invoiceNumber:c.invoiceNumber }, ...rs]);
          setCandidates(cs => cs.filter(c => c.id !== p.id)); setTab('emitidos');
        }
        if (p.action === 'cancelar') setReceipts(rs => rs.map(r => r.id === p.id ? { ...r, canceled: true } : r));
        if (p.action === 'agendar') { const c = candidates.find(c => c.id === p.id)!; setSchedules(ss => [...ss, { id: `agenda-${c.id}`, description: c.description, nextDate: p.date!, active: true, recurring: !!p.recurring, sendEmail: !!p.sendEmail, lastError: null }]); setTab('agendados'); }
        if (p.action === 'agenda') setSchedules(ss => ss.map(s => s.id === p.id ? { ...s, active: !!p.active } : s));
        setNotice({ ok: true, message: p.action === 'email' || p.action === 'compartilhar' ? 'Prévia: nenhum e-mail ou mensagem foi enviado. Na operação, o e-mail leva o PDF e o WhatsApp usa um link válido por 7 dias.' : 'Prévia atualizada. Os dados desta demonstração são fictícios.' });
        setModal(null); return;
      }
      const result = await executarReciboAction(p);
      setNotice(result);
      if (result.ok) {
        setDiscrimination(null);setSignatureModal(false);
        setModal(null);
        if ('path' in result && result.path && p.action === 'compartilhar') {
          const url = `${window.location.origin}${result.path}`;
          setShare(`https://wa.me/?text=${encodeURIComponent(`Olá! Segue seu recibo de pagamento: ${url}`)}`);
        } else {
          if (p.action === 'emitir') setTab('emitidos');
          if (p.action === 'agendar') setTab('agendados');
          router.refresh();
        }
      }
    });
  };
  const active = receipts.filter(r => !r.canceled);
  const match = (s: string) => s.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR'));
  return <div className="mx-auto max-w-6xl space-y-7 px-4 py-8 text-[#141615] dark:text-[#F5F6F4] sm:px-8">
    {props.demo && <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#DFFFAE] px-5 py-3 text-xs font-semibold text-[#2F4A3C]"><span>Prévia local · Dados fictícios · Sem envio de mensagens ou impostos</span><div className="flex gap-3"><a className="underline" href="/previa/recibos?tipo=holding">Holding</a><a className="underline" href="/previa/recibos?tipo=servicos">Outras empresas</a></div></div>}
    <header className="flex flex-wrap items-end justify-between gap-5">
      <div><p className="mb-2 text-[10px] font-bold uppercase tracking-[0.22em] text-[#6E6A61]">Financeiro / {props.holding ? 'Holding patrimonial' : 'Sua empresa'}</p><h1 className="font-serif text-4xl tracking-tight">Recibos</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-[#6E6A61] dark:text-[#A8A49C]">{props.holding ? 'Do aluguel recebido ao documento pronto. Emita, organize e compartilhe em um só lugar.' : 'Comprove os pagamentos recebidos, com a nota fiscal vinculada quando houver.'}</p></div>
      <button onClick={() => { setTab('pendentes'); setSearch(''); }} className="inline-flex items-center gap-2 rounded-full bg-[#141615] px-5 py-3 text-xs font-bold text-[#DFFFAE] dark:bg-[#DFFFAE] dark:text-[#141615]"><Plus size={15} /> Emitir recibo</button>
    </header>
    <div className="grid gap-4 sm:grid-cols-3">
      {[{ label: 'Valor comprovado', value: brl(active.reduce((s,r) => s + r.amount,0)), icon: <FileText size={18} /> }, { label: 'Recibos emitidos', value: String(active.length).padStart(2,'0'), icon: <Check size={18} /> }, { label: 'Emissões agendadas', value: String(schedules.filter(s => s.active).length).padStart(2,'0'), icon: <CalendarDays size={18} /> }].map((c,i) => <div key={c.label} className={`rounded-2xl border border-black/5 p-5 dark:border-white/10 ${i === 0 ? 'bg-[#E7EAE5] dark:bg-[#2F4A3C]' : 'bg-white dark:bg-[#1C201C]'}`}><div className="flex items-center justify-between text-xs text-[#6E6A61] dark:text-[#C8D0C5]"><span>{c.label}</span>{c.icon}</div><p className="mt-4 font-serif text-3xl">{c.value}</p></div>)}
    </div>
    <div className="flex items-start gap-3 rounded-xl border border-black/5 bg-[#F5F6F4] px-4 py-3 dark:border-white/10 dark:bg-[#1C201C]"><FileText size={16} className="mt-0.5 shrink-0 text-[#5F6E46]" /><p className="text-xs leading-relaxed text-[#6E6A61] dark:text-[#A8A49C]">{props.holding ? 'Somente recibos de aluguel de bens da holding podem compor a receita para apuração no ONEFLOW. Os bens pessoais dos sócios ficam separados. A integração aguarda a configuração fiscal.' : 'Este recibo comprova o pagamento e não substitui a nota fiscal. Sua emissão não gera receita adicional nem envio para apuração de impostos.'}</p></div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-black/10 px-4 py-3 dark:border-white/10"><div><p className="text-xs font-semibold">Assinatura eletrônica automática</p><p className="mt-1 text-xs text-[#6E6A61]">{signing ? `Autorizada por ${signing.signerName} · Novos recibos da empresa saem assinados` : 'Desativada · Autorize a assinatura dos novos recibos da empresa no Hub'}</p></div><button disabled={busy} className={actionClass} onClick={()=>setSignatureModal(true)}>{signing ? 'Desativar':'Configurar assinatura'}</button></div>
    {notice && <div role="status" className={`flex items-start justify-between gap-3 rounded-xl p-4 text-sm ${notice.ok ? 'bg-[#EFFFD6] text-[#2F4A3C]' : 'bg-rose-50 text-rose-800'}`}><span>{notice.message}{share && <a target="_blank" rel="noopener noreferrer" className="ml-3 font-bold underline" href={share}>Abrir WhatsApp</a>}</span><button aria-label="Fechar aviso" onClick={() => setNotice(null)}><X size={16}/></button></div>}
    <section className="overflow-hidden rounded-2xl border border-black/10 bg-white dark:border-white/10 dark:bg-[#1C201C]">
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-black/5 px-5 pt-3 dark:border-white/10"><div className="flex gap-5">{(['emitidos','pendentes','agendados'] as const).map(t => <button key={t} onClick={() => setTab(t)} className={`border-b-2 py-4 text-xs font-semibold capitalize ${tab === t ? 'border-[#2F4A3C] text-[#2F4A3C] dark:border-[#DFFFAE] dark:text-[#DFFFAE]' : 'border-transparent text-[#6E6A61]'}`}>{t} <span className="ml-1 text-[10px] opacity-60">{t === 'emitidos' ? receipts.length : t === 'pendentes' ? candidates.length : schedules.length}</span></button>)}</div><label className="mb-3 flex items-center gap-2 rounded-lg bg-[#F5F6F4] px-3 py-2 dark:bg-black/20"><Search size={14} className="text-[#6E6A61]"/><input aria-label="Buscar recibos" value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar cliente ou recibo" className="w-44 bg-transparent text-xs outline-none"/></label></div>
      <div className="divide-y divide-black/5 dark:divide-white/10">
        {tab === 'emitidos' && receipts.filter(r => match(`${r.number} ${r.payer} ${r.description}`)).map(r => <article key={r.id} className={`px-5 py-5 ${r.canceled ? 'opacity-60' : ''}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#F5F6F4] p-3 text-[#2F4A3C] dark:bg-[#2F4A3C] dark:text-[#DFFFAE]"><FileText size={18}/></div><div><h2 className="text-sm font-bold">{r.payer}</h2><p className="mt-1 text-xs text-[#6E6A61] dark:text-[#A8A49C]">{r.description}</p><p className="mt-2 text-[10px] uppercase tracking-wider text-[#6E6A61]">{r.number} · {r.referenceMonth}</p></div></div><div className="text-right"><p className="font-serif text-xl">{brl(r.amount)}</p><span className={`mt-2 inline-block rounded-full px-2.5 py-1 text-[10px] font-bold ${r.canceled ? 'bg-rose-50 text-rose-700' : 'bg-[#EFFFD6] text-[#2F4A3C]'}`}>{r.canceled ? 'Cancelado' : r.signed ? 'Assinado no Hub' : 'Pagamento comprovado'}</span></div></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 pl-0 sm:pl-12"><p className="text-[11px] text-[#6E6A61] dark:text-[#A8A49C]">Recebido em {r.paidAt} · {fiscalLabel[r.oneflowStatus] || r.oneflowStatus}</p>{!r.canceled && <div className="flex flex-wrap gap-1"><a href={pdf(r)} target="_blank" rel="noopener noreferrer" className={actionClass}><ArrowUpRight size={13}/> Ver PDF</a><a href={pdf(r,true)} className={actionClass}><Download size={13}/> Baixar</a><button disabled={busy} onClick={() => setModal({ action:'email',id:r.id })} className={actionClass}><Send size={13}/> E-mail</button><button disabled={busy} onClick={() => run({ action:'compartilhar',id:r.id })} className={actionClass}><Share2 size={13}/> WhatsApp</button><button aria-label={`Cancelar ${r.number}`} disabled={busy} onClick={() => setModal({ action:'cancelar',id:r.id })} className={actionClass}><Ban size={13}/></button></div>}</div></article>)}
        {tab === 'pendentes' && candidates.filter(c => match(`${c.description} ${c.payer || ''}`)).map(c => <article key={c.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5"><div><h2 className="text-sm font-bold">{c.payer || 'Pagador a identificar'}</h2><p className="mt-1 text-xs text-[#6E6A61]">{c.description} · {brl(c.amount)}</p><p className="mt-2 text-[11px] text-[#6E6A61]">{c.status === 'PAID' ? `Recebido em ${fmt(c.paidAt)}` : 'Aguardando pagamento'}{c.invoiceNumber ? ` · NFS-e ${c.invoiceNumber}` : ' · Sem nota vinculada'}</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>setDiscrimination(c)} className={actionClass}>Discriminar valores</button><button disabled={busy} onClick={() => setModal({action:'agendar',id:c.id})} className={actionClass}><Clock3 size={13}/> Agendar</button><button disabled={busy || c.status !== 'PAID' || !c.paidAt} onClick={() => setModal({action:'emitir',id:c.id})} className="rounded-full bg-[#DFFFAE] px-4 py-2.5 text-xs font-bold text-[#2F4A3C] disabled:opacity-40">Emitir recibo</button></div></article>)}
        {tab === 'agendados' && schedules.filter(s => match(s.description)).map(s => <article key={s.id} className="flex flex-wrap items-center justify-between gap-4 px-5 py-5"><div><h2 className="text-sm font-bold">{s.description}</h2><p className="mt-2 text-xs text-[#6E6A61]">{fmt(s.nextDate)} · {s.recurring ? 'Mensal' : 'Emissão única'} · {s.active ? 'Ativo' : 'Pausado'}{s.sendEmail ? ' · E-mail automático' : ''}</p>{s.lastError && <p className="mt-2 text-xs text-rose-700">{s.lastError}</p>}</div><button disabled={busy} className={actionClass} onClick={() => run({action:'agenda',id:s.id,active:!s.active})}>{s.active ? 'Pausar' : 'Retomar'}</button></article>)}
        {(tab === 'emitidos' ? receipts.filter(r => match(`${r.number} ${r.payer} ${r.description}`)) : tab === 'pendentes' ? candidates.filter(c => match(`${c.description} ${c.payer || ''}`)) : schedules.filter(s => match(s.description))).length === 0 && <div className="px-6 py-14 text-center"><FileText className="mx-auto mb-3 text-[#6E6A61]" size={25}/><p className="text-sm font-semibold">Nenhum resultado por aqui</p><p className="mt-2 text-xs text-[#6E6A61]">{tab === 'pendentes' ? 'Os recebimentos sem recibo aparecem nesta aba.' : tab === 'agendados' ? 'Agende a emissão a partir de um recebimento pendente.' : 'Escolha um pagamento na aba Pendentes para emitir seu primeiro recibo.'}</p></div>}
      </div>
    </section>
    {signatureModal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-label="Assinatura automática" className="w-full max-w-lg space-y-5 rounded-3xl bg-[#F5F6F4] p-7 text-[#141615]" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);run({action:'assinatura',id:'config',active:!signing,consent:fd.get('consent')==='on'});}}><div className="flex justify-between"><h2 className="font-serif text-2xl">{signing ? 'Desativar assinatura':'Autorizar assinatura automática'}</h2><button type="button" onClick={()=>setSignatureModal(false)}>Fechar</button></div>{signing ? <p className="text-sm">Os próximos recibos terão espaço para assinatura manual. As assinaturas dos recibos anteriores continuam registradas.</p> : <><p className="text-sm leading-relaxed">O Hub registra sua identidade, a autorização, a data da emissão e a integridade do documento. A assinatura fica no PDF e na consulta pelo QR code.</p><label className="flex items-start gap-3 text-sm"><input name="consent" type="checkbox" required className="mt-1"/><span>Autorizo o Hub a assinar eletronicamente os futuros recibos desta empresa em meu nome, inclusive emissões agendadas. Confirmo que represento o recebedor. A autorização vale até ser desativada e não inclui bens pessoais dos sócios.</span></label><p className="text-xs text-[#6E6A61]">Requer o usuário pessoal do responsável da empresa, com nome, CPF e cadastro aprovado. Assinatura eletrônica interna do Hub.</p></>}{props.demo && <p className="text-xs text-amber-800">Prévia fictícia: esta ação não registra uma autorização real.</p>}<button disabled={busy} className="w-full rounded-full bg-[#2F4A3C] p-3 text-sm font-semibold text-[#DFFFAE]">{busy ? 'Processando…' : signing ? 'Desativar para novos recibos':'Autorizar assinatura automática'}</button></form></div>}
    {discrimination && <Discriminacao candidate={discrimination} expenses={props.expenses || []} busy={busy} onClose={()=>setDiscrimination(null)} onSave={itens=>run({action:"discriminar",id:discrimination.id,itens})}/>}
    {modal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form role="dialog" aria-modal="true" aria-labelledby="receipt-dialog-title" onSubmit={e => { e.preventDefault(); const fd = new FormData(e.currentTarget); run({ ...modal, email: String(fd.get('email') || ''), name: String(fd.get('name') || ''), reason: String(fd.get('reason') || ''), date: String(fd.get('date') || ''), recurring: fd.get('recurring') === 'on', sendEmail: fd.get('sendEmail') === 'on', ...(modal.action==='emitir' ? {sign:fd.get('sign')==='on'} : {}) }); }} className="w-full max-w-md space-y-5 rounded-3xl bg-[#F5F6F4] p-7 dark:bg-[#141615]"><div className="flex items-center justify-between"><h2 id="receipt-dialog-title" className="font-serif text-2xl">{modal.action === 'email' ? 'Enviar recibo' : modal.action === 'cancelar' ? 'Cancelar recibo' : modal.action === 'emitir' ? 'Emitir recibo' : 'Agendar emissão'}</h2><button type="button" aria-label="Fechar" onClick={() => setModal(null)}><X size={18}/></button></div>
      {modal.action === 'email' && <label className="block space-y-2 text-xs"><span>E-mail do destinatário</span><input autoFocus type="email" name="email" required className={inputClass}/><p className="text-[#6E6A61]">O PDF será enviado como anexo.</p></label>}
      {modal.action === 'emitir' && !candidates.find(c=>c.id===modal.id)?.payer && <label className="block space-y-2 text-xs"><span>Nome de quem pagou</span><input autoFocus name="name" required maxLength={200} className={inputClass}/></label>}
      {modal.action==='emitir' && <><label className="flex items-center gap-2 text-sm"><input name="sign" type="checkbox" defaultChecked={!!signing && candidates.find(c=>c.id===modal.id)?.ownerType!=='PF'} disabled={!signing || candidates.find(c=>c.id===modal.id)?.ownerType==='PF'}/> Assinar eletronicamente este recibo</label><p className="text-xs text-[#6E6A61]">{signing && candidates.find(c=>c.id===modal.id)?.ownerType!=='PF' ? `Assinatura autorizada por ${signing.signerName}. Desmarque para emitir sem assinatura.` : 'Emissão sem assinatura eletrônica. Para assinar recibos da empresa, configure a autorização do responsável.'}</p></>}
      {modal.action === 'cancelar'  && <label className="block space-y-2 text-xs"><span>Motivo do cancelamento</span><textarea autoFocus name="reason" required minLength={5} className={inputClass}/><p className="text-[#6E6A61]">O recibo ficará no histórico. O pagamento e a nota fiscal continuam registrados.</p></label>}
      {modal.action === 'agendar' && <><label className="block space-y-2 text-xs"><span>Data da emissão</span><input autoFocus type="date" name="date" required min={props.demo ? '2026-09-30' : new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})} className={inputClass}/></label>{candidates.find(c => c.id === modal.id)?.leaseId && <label className="flex items-center gap-2 text-xs"><input type="checkbox" name="recurring"/> Repetir todo mês para este aluguel</label>}<label className="flex items-center gap-2 text-xs"><input type="checkbox" name="sendEmail"/> Enviar por e-mail após emitir</label><p className="text-xs leading-relaxed text-[#6E6A61]">A emissão aguarda a confirmação do pagamento. Se houver uma pendência, ela aparecerá na agenda.</p></>}
      <button disabled={busy} className="w-full rounded-full bg-[#2F4A3C] p-3 text-xs font-bold text-[#DFFFAE] disabled:opacity-50">{busy ? 'Processando…' : modal.action === 'email' ? 'Enviar PDF' : modal.action === 'cancelar' ? 'Confirmar cancelamento' : modal.action === 'emitir' ? 'Emitir recibo' : 'Salvar agendamento'}</button>
    </form></div>}
  </div>;
}
